version: '3'

services:
  db:
    image: postgres
    ports:
      - '5432:5432' 
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    environment: 
      POSTGRES_PASSWORD: 'postgres' 
  api:
    build: 
      context: ./api/
      dockerfile: Dockerfile
    command: /bin/sh -c "rm -f /myapp/tmp/pids/server.pid && bundle exec puma -C config/puma.rb"
    volumes:
      - ./api:/myapp:delegated
      - public-data:/myapp/public
      - tmp-data:/myapp/tmp
      - log-data:/myapp/log
    depends_on:
      - db
    tty: true
    stdin_open: true
  nginx:
    build:
      context: ./api/nginx
      dockerfile: Dockerfile
    restart: always 
    volumes:
      - public-data:/myapp/public
      - tmp-data:/myapp/tmp
    ports:
      - 80:80
    depends_on:
      - api
  # front:
  #   build: 
  #     context: ./front/
  #     dockerfile: Dockerfile
  #   stdin_open: true
  #   tty: true
  #   volumes:
  #     - ./front:/usr/src/app:delegated
  #   command: /bin/sh -c "yarn start"
  #   ports:
  #     - "8000:3000"
volumes:
  postgresql-data:
  public-data:
  tmp-data:
  log-data:
    driver: local